Fix Python 2->3, Portuguese->Spanish, dead URLs, variable typos, security bugs

diff --git a/Modulos/v2raymanager b/Modulos/v2raymanager
--- a/Modulos/v2raymanager
+++ b/Modulos/v2raymanager
@@ -9,11 +9,11 @@ GREEN='\033[1;32m'
 YELLOW='\033[1;33m'
 SCOLOR='\033[0m'
 msg01='\033[1;37m\033[1;33mUsuario Nulo\033[1;31m'
-msg02='\033[1;37m\033[1;33mNombre mui corto (MIN: 2 CARACTERS)\033[1;31m'
-msg03='\033[1;37m\033[1;33mNombre mui grande (MAX: 5 CARACTERES)\033[1;31m'
+msg02='\033[1;37m\033[1;33mNombre muy corto (MIN: 2 CARACTERES)\033[1;31m'
+msg03='\033[1;37m\033[1;33mNombre muy grande (MAX: 5 CARACTERES)\033[1;31m'
 msg04='\033[1;37m\033[1;33mContraseña Nula\033[1;31m'
-msg05='\033[1;37m\033[1;33mContraseña muito curta\033[1;31m'
-msg06='\033[1;37m\033[1;33mContraseña muito grande\033[1;31m'
+msg05='\033[1;37m\033[1;33mContraseña muy corta\033[1;31m'
+msg06='\033[1;37m\033[1;33mContraseña muy larga\033[1;31m'
 msg07='\033[1;37m\033[1;33mDuracion Nula\033[1;31m'
 msg08='\033[1;37m\033[1;33mDuracion invalida, utilize números\033[1;31m'
 msg09='\033[1;37m\033[1;33mDuracion máxima de un ano\033[1;31m'
@@ -23,26 +23,26 @@ msg13='\033[1;37m\033[1;33mLimite maximo de 999\033[1;31m'
 msg14='\033[1;37m\033[1;33mUsuario Ya Existe\033[1;31m'
 msg15='\033[1;37m\033[1;33m(Solo numeros) GB = Min: 1gb Max: 1000gb\033[1;31m'
 msg16='\033[1;37m\033[1;33m(Solo numeros)\033[1;31m'
-msg17='\033[1;37m\033[1;33m(Sim imformacion - Para Cancelar Digite CRTL + C)\033[1;31m'
+msg17='\033[1;37m\033[1;33m(Sin informacion - Para Cancelar Digite CTRL + C)\033[1;31m'
 [[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@Netxxus" ]] && {
     err_fun () {
         case $1 in
-        1)msg -verm "$(fun_trans "Usuário Nulo")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-        2)msg -verm "$(fun_trans "Nombre mui corto (MIN: 2 CHARACTERS)")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-        3)msg -verm "$(fun_trans "Nombre mui grande (MAX: 5 CARACTERES)")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-        4)msg -verm "$(fun_trans "Senha Nula")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-        5)msg -verm "$(fun_trans "Paswors mui corta")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-        6)msg -verm "$(fun_trans "Pasword mui grande")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+        1)msg -verm "$(fun_trans "Usuario Nulo")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+        2)msg -verm "$(fun_trans "Nombre muy corto (MIN: 2 CARACTERES)")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+        3)msg -verm "$(fun_trans "Nombre muy grande (MAX: 5 CARACTERES)")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+        4)msg -verm "$(fun_trans "Contrasena Nula")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+        5)msg -verm "$(fun_trans "Password muy corta")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+        6)msg -verm "$(fun_trans "Password muy larga")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
         7)msg -verm "$(fun_trans "Duracion Nula")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-        8)msg -verm "$(fun_trans "Duracion invalida, utilize números")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-        9)msg -verm "$(fun_trans "Duracion maxima de um ano")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+        8)msg -verm "$(fun_trans "Duracion invalida, utilize numeros")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+        9)msg -verm "$(fun_trans "Duracion maxima de un ano")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
         11)msg -verm "$(fun_trans "Limite Nulo")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-        12)msg -verm "$(fun_trans "Limite invalido, utilize números")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-        13)msg -verm "$(fun_trans "Limite máximo de 999")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+        12)msg -verm "$(fun_trans "Limite invalido, utilize numeros")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+        13)msg -verm "$(fun_trans "Limite maximo de 999")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
         14)msg -verm "$(fun_trans "Usuario Ya Existe")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-	    15)msg -verm "$(fun_trans "(Solo números) GB = Min: 1gb Max: 1000gb")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-	    16)msg -verm "$(fun_trans "(Solo números)")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
-	    17)msg -verm "$(fun_trans "(Sim imformacion - Para Cancelar Digite CRTL + C)")"; sleep 4s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+	    15)msg -verm "$(fun_trans "(Solo numeros) GB = Min: 1gb Max: 1000gb")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+	    16)msg -verm "$(fun_trans "(Solo numeros)")"; sleep 2s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
+	    17)msg -verm "$(fun_trans "(Sin informacion - Para Cancelar Digite CTRL + C)")"; sleep 4s; tput cuu1; tput dl1; tput cuu1; tput dl1;;
         esac
     }
 
@@ -218,7 +218,7 @@ msg17='\033[1;37m\033[1;33m(Sim imformacion - Para Cancelar Digite CRTL + C)\033
     local RETURN="$(cat $HOST|cut -d'|' -f2)"
     local IDEUUID="$(cat $HOST|cut -d'|' -f1)"
     if [[ -z $RETURN ]]; then
-    echo -e "----- NENHUM USUARIO REGISTRADO -----"
+    echo -e "----- NINGUN USUARIO REGISTRADO -----"
     echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
     fun_v2raymanager
     else
@@ -265,7 +265,7 @@ msg17='\033[1;37m\033[1;33m(Sim imformacion - Para Cancelar Digite CRTL + C)\033
     local RETURN="$(cat $HOST|cut -d'|' -f2)"
     local IDEUUID="$(cat $HOST|cut -d'|' -f1)"
     if [[ -z $RETURN ]]; then
-    echo -e "----- NENHUMA PORTA REGISTRADA -----"
+    echo -e "----- NINGUN PUERTO REGISTRADO -----"
     echo -e "\033[1;37m• \033[1;33mEnter Para Continuar\033[1;31m" && read enter
     fun_v2raymanager
     else
@@ -396,7 +396,7 @@ msg17='\033[1;37m\033[1;33m(Sim imformacion - Para Cancelar Digite CRTL + C)\033
     echo -e "\033[1;37m\033[1;33m[2] > RESETAR DATOS DE PUERTO\033[1;31m"
     echo -e "\033[1;37m\033[1;33m[3] > VER DATOS CONSUMIDOS\033[1;31m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
-    echo -e "\033[1;32m [0] > \e[97m\033[1;41m VOLTAR \033[1;37m"
+    echo -e "\033[1;32m [0] > \e[97m\033[1;41m VOLVER \033[1;37m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
     selection=$(selection_fun 3)
     case ${selection} in
@@ -421,7 +421,7 @@ msg17='\033[1;37m\033[1;33m(Sim imformacion - Para Cancelar Digite CRTL + C)\033
     fi
     unset PID_GEN
     PID_GEN=$(ps x|grep -v grep|grep "limv2ray")
-    [[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESATIVADO ] " || PID_GEN="\e[92m [ ATIVADO ] "
+    [[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESACTIVADO ] " || PID_GEN="\e[92m [ ACTIVADO ] "
     statgen="$(echo $PID_GEN)"
     clear 
     clear
@@ -442,7 +442,7 @@ msg17='\033[1;37m\033[1;33m(Sim imformacion - Para Cancelar Digite CRTL + C)\033
     local range
     for((i=0; i<=$1; i++)); do range[$i]="$i "; done
     while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
-    echo -ne "\033[1;37m ► Selecione uma Opção: " >&2
+    echo -ne "\033[1;37m ► Seleccione una Opcion: " >&2
     read selection
     tput cuu1 >&2 && tput dl1 >&2
     done
@@ -450,23 +450,23 @@ msg17='\033[1;37m\033[1;33m(Sim imformacion - Para Cancelar Digite CRTL + C)\033
     }
 
     PID_GEN=$(ps x|grep -v grep|grep "limv2ray")
-    [[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESATIVADO ] " || PID_GEN="\e[92m [ ATIVADO ] "
+    [[ ! $PID_GEN ]] && PID_GEN="\e[91m [ DESACTIVADO ] " || PID_GEN="\e[92m [ ACTIVADO ] "
     statgen="$(echo $PID_GEN)"
     #SPR & 
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
 
     fun_v2raymanager() {
-		while true $x != "ok"; do
+		while true; do
 			[[ ! -e '/home/sshplus' ]] && exit 0
 			clear
 			echo -e "\E[44;1;37m                MENU V2RAY                 \E[0m\n"
 
 			xv2ray1=`if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
-			echo -e "\e[92m ATIVADO"
+			echo -e "\e[92m ACTIVADO"
 			else
-			echo -e "\e[91m DESATIVADO"
+			echo -e "\e[91m DESACTIVADO"
 			fi`;
-            echo -e "\033[1;32mSERVICIO: \033[1;33mV2RAY \033[1;32m$xv2ray1\033[1;37m" 
+			echo -e "\033[1;32mESTADO: \033[1;33mV2RAY \033[1;32m$xv2ray1\033[1;37m" 
 			xv2ray=`if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
 			echo -e "\033[1;32m◉ "
 			else
@@ -493,7 +493,7 @@ msg17='\033[1;37m\033[1;33m(Sim imformacion - Para Cancelar Digite CRTL + C)\033
 			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
 			echo ""
 			tput civis
-			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m "
+			echo -ne "\033[1;32mQUE DESEA HACER \033[1;33m?\033[1;31m?\033[1;37m "
 			read x
 			tput cnorm
 			clear
@@ -540,13 +540,13 @@ msg17='\033[1;37m\033[1;33m(Sim imformacion - Para Cancelar Digite CRTL + C)\033
 				;;
 
 			0 | 00)
-				echo -e "\033[1;31mSaindo...\033[0m"
+				echo -e "\033[1;31mSaliendo...\033[0m"
 				sleep 2
 				clear
 				exit
 				;;
 			*)
-				echo -e "\033[1;31mOpcao invalida !\033[0m"
+				echo -e "\033[1;31mOpcion invalida !\033[0m"
 				sleep 2
 				;;
 			esac
